openapi: 3.0.0
info:
  title: vpn-backend
  version: '1.0'
  contact:
    name: Grant Unwin
    email: grant@grantunw.in
  description: VPN app backend
servers:
  - url: 'http://localhost:3000'
paths:
  /countries:
    get:
      summary: Your GET endpoint
      tags:
        - country
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/country'
      operationId: get-countries
      description: Get a list of countries available
  '/countries/{id}/servers':
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        description: The country ID
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/server'
      operationId: get-countries-id-servers
      description: A list of servers available for this country
      parameters: []
components:
  schemas:
    country:
      title: country
      type: object
      x-examples:
        example country:
          id: 1
          name: United Kingdom
      properties:
        id:
          type: integer
        name:
          type: string
        icon:
          type: string
    server:
      title: server
      type: object
      properties:
        id:
          type: integer
        country:
          type: integer
          format: int32
          example: 1
          minimum: 0
          multipleOf: 1
        address:
          type: string
        protocols:
          type: string
          enum:
            - ipsec
            - openvpn
tags:
  - name: country
