openapi: 3.0.0
info:
  title: vpn-backend
  version: '1.0'
  contact:
    name: Grant Unwin
    email: grant@grantunw.in
  description: VPN app backend
servers:
  - url: 'http://vpn-backend-express.azurewebsites.net'
paths:
  /countries:
    get:
      x-eov-operation-handler: countriesRoute
      summary: getCountries
      tags:
        - country
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/country'
      operationId: countriesGet
      description: Get a list of countries available
      security: []
  /register:
    post:
      x-eov-operation-handler: accountRoute
      summary: postRegister
      operationId: registerPost
      description: adasd
      tags:
        - auth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/register'
  /subscriptions:
    get:
      x-eov-operation-handler: accountRoute
      summary: getSubscriptions
      tags:
        - account
      description: sd
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/subscription'
        '401':
          description: Unauthorized
      operationId: subscriptionsGet
      security:
        - oauth2:
            - phone
            - email
            - openid
            - profile
  /account:
    get:
      x-eov-operation-handler: accountRoute
      operationId: accountGet
      summary: getAccount
      description: da
      tags:
        - account
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'
        '401':
          description: Unauthorized
      security:
        - oauth2:
            - openid
            - phone
            - email
            - profile
  /login:
    post:
      x-eov-operation-handler: accountRoute
      summary: postLogin
      tags:
        - auth
      description: da
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
      operationId: loginPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
  /subscription/android:
    parameters: []
    post:
      x-eov-operation-handler: subscriptionRoute
      description: Report a new android IAP subscription
      summary: androidSubscriptionPost
      operationId: androidSubscriptionPost
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/androidSubscription'
      tags:
        - subscription
      security:
        - oauth2:
            - phone
            - email
            - openid
            - profile
  /subscription/stripe:
    post:
      x-eov-operation-handler: subscriptionRoute
      summary: stripeSubscriptionPost
      operationId: stripeSubscriptionPost
      responses:
        '200':
          description: OK
      security:
        - oauth2:
            - profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/stripeSubscription'
      description: 'Post the product and stripe payment method Id, that API will attempt to create the subscription for the current logged in user, and charge the payment method if necessary.'
      tags:
        - subscription
components:
  schemas:
    country:
      title: country
      type: object
      x-examples:
        example country:
          id: 1
          name: United Kingdom
      properties:
        id:
          type: integer
        name:
          type: string
        icon:
          type: string
        cities:
          type: array
          items:
            $ref: '#/components/schemas/city'
      required:
        - id
        - name
        - icon
        - cities
    server:
      title: server
      type: object
      x-examples:
        server 1:
          id: 1
          address: 1.1.1.1
          protocols: ipsec
          username: vpnuser
          password: password
          ipSecPsk: sharedKey
      properties:
        id:
          type: integer
        address:
          type: string
        protocols:
          type: string
          enum:
            - ipsec
            - openvpn
        username:
          type: string
        password:
          type: string
        ipSecPsk:
          type: string
        caCert:
          type: string
        clientCert:
          type: string
        certAlias:
          type: string
        certPassword:
          type: string
        name:
          type: string
    city:
      title: city
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        servers:
          type: array
          items:
            $ref: '#/components/schemas/server'
      required:
        - id
        - name
        - servers
    register:
      title: register
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    subscription:
      title: subscription
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: string
        oldPrice:
          type: string
        description:
          type: string
    account:
      title: account
      type: object
      properties:
        subscribed:
          type: boolean
        email:
          type: string
      required:
        - subscribed
        - email
    login:
      title: login
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    loginResponse:
      title: loginResponse
      type: object
      properties:
        token:
          type: string
      required:
        - token
    errorResponse:
      title: errorResponse
      type: object
      x-examples:
        Bad Login:
          status: error
          mesage: Incorrect username and password combination
      description: General Error Response
      properties:
        status:
          type: string
        message:
          type: string
      required:
        - status
        - message
    androidSubscription:
      title: androidSubscription
      type: object
      properties:
        packageName:
          type: string
        subscriptionId:
          type: string
        token:
          type: string
      required:
        - packageName
        - subscriptionId
        - token
      description: ''
    stripeSubscription:
      title: stripeSubscription
      type: object
      properties:
        stripePaymentMethodId:
          type: string
        productId:
          type: number
        channelId:
          type: number
        currencyId:
          type: number
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://guvpn.auth.eu-west-2.amazoncognito.com/oauth2/authorize?&client_id=chsornstdm0tkj3q3lag3ee8o'
          refreshUrl: 'https://guvpn.auth.eu-west-2.amazoncognito.com/oauth2/authorize?&client_id=chsornstdm0tkj3q3lag3ee8o'
          scopes:
            phone: phone
            email: email
            openid: openid
            profile: profile
            aws.cognito.signin.user.admin: aws.cognito.signin.user.admin
tags:
  - name: country
  - name: auth
  - name: account
  - name: subscription
