openapi: 3.0.0
info:
  title: vpn-backend
  version: '1.0'
  contact:
    name: Grant Unwin
    email: grant@grantunw.in
  description: VPN app backend
servers:
  - url: 'http://localhost:3000'
paths:
  /countries:
    get:
      x-eov-operation-handler: countriesRoute
      summary: Your GET endpoint
      tags:
        - country
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/country'
      operationId: countriesGet
      description: Get a list of countries available
      security: []
  /register:
    get:
      x-eov-operation-handler: accountRoute
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
      operationId: registerPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/register'
      security: []
      description: ''
  /subscriptions:
    get:
      x-eov-operation-handler: accountRoute
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/subscription'
        '401':
          description: Unauthorized
      operationId: subscriptionsGet
  /account:
    get:
      x-eov-operation-handler: accountRoute
      operationId: accountGet
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/account'
        '401':
          description: Unauthorized
  /login:
    post:
      x-eov-operation-handler: accountRoute
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginResponse'
        '401':
          description: Unauthorized
      operationId: loginPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
components:
  schemas:
    country:
      title: country
      type: object
      x-examples:
        example country:
          id: 1
          name: United Kingdom
      properties:
        id:
          type: integer
        name:
          type: string
        icon:
          type: string
        cities:
          type: array
          items:
            $ref: '#/components/schemas/city'
    server:
      title: server
      type: object
      properties:
        id:
          type: integer
        country:
          type: integer
          format: int32
          example: 1
          minimum: 0
          multipleOf: 1
        address:
          type: string
        protocols:
          type: string
          enum:
            - ipsec
            - openvpn
    city:
      title: city
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        servers:
          type: array
          items:
            $ref: '#/components/schemas/server'
    register:
      title: register
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    subscription:
      title: subscription
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: string
        oldPrice:
          type: string
        description:
          type: string
    account:
      title: account
      type: object
      properties:
        subscribed:
          type: boolean
    login:
      title: login
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    loginResponse:
      title: loginResponse
      type: object
      properties:
        token:
          type: string
tags:
  - name: country
